POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaGlsMjMiLCJpZCI6IjYzMDY1YWYwMWJjZTQxMzdlNjVjYTQxYSIsImlhdCI6MTY2NTY4MDM5MiwiZXhwIjoxNjY1NjgzOTkyfQ.qRkzQGON6RLbb1ruobZHeWU3501VNFyU4-tLjBmjASw

{
  "title": "i'm adding this tonight!",
  "author": "sahil",
  "url": "abcd.com",
  "likes": 1
}